### ISSUE TITLE
@nksauter code review May 17

### ISSUE THREAD

**Issue by nksauter** [dermen/sim_erice#1]
Good initial implementation but lots of work to do in the next few days.  Some observations to start with:

- [x] 1) Running the script with no parameters gives helpless traceback:
Exception ignored in: <function command_stream.__del__ at 0x7f2a1cef6160>
Traceback (most recent call last):
  File "/pscratch/sd/n/nksauter/edge/alcc-recipes/cctbx/modules/cctbx_project/iotbx/shelx/lexer.py", line 35, in __del__
    self.file.close()
AttributeError: 'command_stream' object has no attribute 'file'
Traceback (most recent call last):
  File "/pscratch/sd/n/nksauter/edge/alcc-recipes/cctbx/modules/sim_erice/sim_view.py", line 306, in <module>
    frame = SimView(root, params, pdbfile)
  File "/pscratch/sd/n/nksauter/edge/alcc-recipes/cctbx/modules/sim_erice/sim_view.py", line 43, in __init__
    sg = str(symmetry.space_group_info())
AttributeError: 'NoneType' object has no attribute 'space_group_info'

- [x] 2) Would like program to use its own PDB file if none is provided

- [x] 3) Attempts to get command line help ("-h") should work

- [x] 4) Help text could include the ability to download PDB files with "iotbx.fetch_pdb"

- [x] 5) Please let's have the beam center near the lower left corner as in the original simulator, so the limited screen real estate can be more focused on higher-angle scattering.

- [x] 6) Please have each unit cell parameter independently adjustable.

- [x] 7) The screen readout for missetting angles could not possibly be in degrees!  Something is wrong with the units.

- [x] 8) Some of the parameters need much finer granularity per arrow click.  For example, the mimimum mosaic angle is 0.3 degree, but it should be continuously adjustable down to 0.0.

- [x] 9) Adjusting the MosDom size scales the intensity up.  This should not be the behavior of the simulator.  Instead, the simulation should treat the overall crystal size as constant, so the spot intensities are always roughly on the same scale, and visible to the corners.  The MosDom parameter should more-or-less be inversely coupled with a hidden "number-of-domains" parameter such that the overall crystal size remains constant.

**Comment by dermen** [comment]
I added checkboxes to the action items in the above comment  , if one of the items is checked off, then simply edit that comment and change the markdown code from e.g.,   ```"- [ ] 1)"``` to ```"- [x] 1)"``` ..

**Comment by nksauter** [comment]
More issues to address

- [ ] 10) Toggle image mode button should say "Toggle reference"
- [ ] 11) It should only have two modes: either the reference is on or off.  Default off.
- [ ] 12) The color of the "current simulation" should remain the same (cyan) whether or not the reference is shown.
- [ ] 13) Default bandwidth should be 0.3%
- [ ] 14) Currently there is a ZeroDivisionError when trying to set bandwidth to zero.  Please rework this so the useful range is 0.01% to 5%.
- [ ] 15) Default domain size should be 30x30x30
- [ ] 16) Default mosaic angle should be 0.1 degree with useful range from 0.01 to 5.
- [ ] 17) The default energy of 6750 is a very unusual value.  Can we please make the default 9500 eV (a reasonable XFEL value) and set the range from 6500 to 12000?  Steps could be 25 (small) and 250 (large).
- [ ] 18) Setting the spectrum shape to SASE should not erase the "Energy" display.  Energy should still be displayed as the nominal energy.

**Comment by irisdyoung** [comment]
Question on #10-12: earlier you requested a grayscale mode, and I do find the colorful (2nd) mode to be useful. Can we have a default mode that does what you describe and a different button to retain the current behavior and cycle through alternative display modes?

**Comment by irisdyoung** [comment]
Question on #18: the rationale for this was that previously we could select the "energy" dial and could see the description changing without it affecting the simulation in SASE mode. I could update the menu to not have an "energy" option in this mode. Otherwise I think we need some other warning to the user that we're not changing what's displayed. What do you prefer?

**Comment by nksauter** [comment]
Question on #10-12: I'm not sure what your point of view is.  Do you prefer the grayscale mode?  Despite having requested it, to my eyes it is just an annoyance, having to cycle through three modes, whereas all I want to really do is turn the reference on or off.  Mostly off, because I want to focus on the live simulation.  Keep in mind please, my view that the reference image is simply a placeholder for the eventual ability to display actual data compared to the current simulation.

**Comment by nksauter** [comment]
Question on #18: I suppose that in SASE mode, the action of the energy dial should be to restart the iterator with a new principal energy.  The new spectrum iterator would supercede the old one that is set here: https://github.com/dermen/sim_erice/blob/b8601ee37881cd06cca1ed82d8d7b7b634fc78e3/command_line/sim_view.py#L183

**Comment by irisdyoung** [comment]
Ok, addressed all the above.

Remaining issues from before the weekend:
[ ] 19) Expand stencil for diffuse scattering
[ ] 20) Update diffuse scattering helpstring
[ ] 21) Rotation mode resembling a synchrotron experiment

**Comment by irisdyoung** [comment]
I believe subtask 19 has been addressed by now.
