### ISSUE TITLE
Add Felix to permitted developers

### ISSUE THREAD

**Issue by nksauter** [dermen/sim_erice#14]
Can't figure out how to add a new developer.  Someone else knows?

**Comment by irisdyoung** [comment]
![Screenshot 2023-05-08 at 17 59 18](https://user-images.githubusercontent.com/14185571/236967796-0b4625c4-5256-4a41-9733-6de65a1637c5.png)
This is how you'd do it, but I think we don't have the necessary permissions since these aren't showing up for us.
