### ISSUE TITLE
Add a phil scope

### ISSUE THREAD

**Issue by nksauter** [dermen/sim_erice#16]
Set important hyperparameters in Phil, to expose them for power users.  Parameters should include mosaic_domains, oversampling, total rotation width, and perhaps others.

**Comment by nksauter** [comment]
@irisdyoung just as a point of communication, I had intended the new phil scope to have three parameters only (mosaic_domains, oversampling, and total_rotation_width).  I see the new code in the commit c5ab465 encapsulates dozens of parameters that populate the menu.  While trying to remain neutral I do feel that it was a lot of lines of code that I hadn't intentionally asked for.

**Comment by irisdyoung** [comment]
I see. I thought we had discussed earlier making it possible for the user to adjust e.g. the step size, or to set a different default spectrum when loading the simulation, and that those were among the hyperparameters you were requesting. And given that, it seemed to just make sense to encapsulate the other dictionary elements in the same place, to avoid having to keep track of the same collections in two different places. Do you agree with that design choice or would you prefer to have the phil much narrower in scope?

**Comment by nksauter** [comment]
- Regarding step size, I'd like to make a concerted effort to choose illustrative default step sizes so the user can see effects on the pattern without messing with the defaults.  Otherwise we have failed the teaching mission.  In my opinion the previous dictionary implementation of parameters had the advantage of being compact, easily located, and understandable to the power user. 
- I'm not aware of the discussion of the default spectrum.  Do you refer to SASE spectrum?  I remember in previous versions we could choose the SASE event, but I do not see any controls for that here.

**Comment by nksauter** [comment]
- Just to be clear I am not asking for mosaic_domains, oversampling, and total rotation width to be GUI controls.  Rather, I feel we need them as developers to be able to understand problems such as why the Bragg spots appear to be broken as in Issue #25 .

**Comment by irisdyoung** [comment]
Step size: considering a user might choose a different PDB, might it be possible they will need different defaults? Especially if it's a very different size ucell?

Spectrum: while I recognize that the target use case is GPU, making it possible to initiate in monochromatic mode makes it possible to run on CPU (at all). 

We can still change between SASE pulses with the "New Pulse" button.

Hyperparams: understood, they will be exposed as phil and/or command line params only.
