### ISSUE TITLE
SASE and Gaussian spectra don't produce any signal after randomize orientation

### ISSUE THREAD

**Issue by irisdyoung** [dermen/sim_erice#2]
After randomizing orientation (once or any number of times), only monochromatic spectrum mode produces an image. This is not fixed with the "reset all" button.

**Comment by dermen** [comment]
My guess is the call to instantiate_diffBragg in the `randomize_orientation` method . Really instantiate_diffBrag should only ever be called once, calling it multiple times can lead to unpredictable behavior. I suggest:

```
def randomize_orientation(SIM, seed_rand=32, seed_mersenne=0):
    # do a sanity test for instantiation, e.g. assert SIM.D is not None
    mersenne_twister = flex.mersenne_twister(seed=seed_mersenne)
    scitbx.random.set_random_seed(seed_rand)
    rand_norm = scitbx.random.normal_distribution(mean=0, sigma=2)
    g = scitbx.random.variate(rand_norm)
    rot = g(1)
    site = scitbx.matrix.col(mersenne_twister.random_double_point_on_sphere())
    ori = site.axis_and_angle_as_r3_rotation_matrix(rot[0],deg=False)
    SIM.crystal.dxtbx_crystal.set_U(ori)  # optional
    SIM.D.Umatrix = ori  # ori here should be a tuple of 9 numbers, so you might need to do ori.elem or something (not sure)

**Comment by irisdyoung** [comment]
Amazing! Reading my history it looks like I didn't notice any of the capital lettered attributes when I tried `dir(SIM.D)` ... I didn't see Umatrix at all. Local branch is clean. Would you like to push the fix?

**Comment by dermen** [comment]
sure thing,  I just pushed
