### ISSUE TITLE
Simplify the "use structure factors" control

### ISSUE THREAD

**Issue by nksauter** [dermen/sim_erice#21]
Since it is a binary choice, no need to make the user look at a pull down menu.  Would a push button suffice?

**Comment by irisdyoung** [comment]
I prefer radio buttons or checkboxes over a button in this case because a button can leave it ambiguous which option is currently active. Reopen the issue if you want to override this though.

**Comment by nksauter** [comment]
For the record my criticism of radio boxes is that the user needs to move the mouse in order to repeatedly exercise the toggle.  The user's visual attention should be on the diffraction pattern, not the controls.  However, let's make one quick fix for the moment and then close the issue.  Please make the radio button much bigger (at least two-fold the diameter) so the mousing does not have to be ultraprecise.

**Comment by irisdyoung** [comment]
Closed with commit, but for the record: pressing anywhere in the text region already activates the radio button in "button" shape, but I've switched it to appearing to be a button to make that more clear. It doesn't seem to be possible to resize the circle indicator.

It's possible to create another button with a label and purpose of cycling between options. Either in combination with other buttons/radio boxes, or next to a menu. What's your preference? (Leaving this for later regardless.)
