### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by nksauter** [dermen/sim_erice#29]
Per @mewall keep the program behavior as is but make some recommendations to the user about investigating diffuse scattering in some documentation: (1) speed things up by using Monochromatic spectrum shape; (2) increase domain size to 10000 Angstroms to more easily see what happens when changing diffuse scattering parameters.

**Comment by nksauter** [comment]
Actually the documentation appears twice, in both the sim_view.py and the README.md, so ultimately it needs to be updated in both places.

**Comment by irisdyoung** [comment]
Addressed by a09c975a57fadb05ce856663d099c9e7423bb51d (reopen if specific topics need addressing within the documentation)
