### ISSUE TITLE
Parameterize mosaic domains

### ISSUE THREAD

**Issue by irisdyoung** [dermen/sim_erice#38]
Subtask of #16

**Comment by nksauter** [comment]
It's not working correctly.  I specify mosaic_domains=1000000000 at the command line but in the program, repeatedly clicking up arrow on roty, it still takes only 0.12 seconds in add_diffBragg.

**Comment by nksauter** [comment]
seemingly fixed by a series of commits regarding mosaic domains

**Comment by nksauter** [comment]
```mosaic_domains_diffuse``` does not work correctly.
Problem statement:  I am using the default values (```mosaic_domains_bragg=100 mosaic_domains_diffuse=10```).
However, when I switch from Diffuse scattering Off to On, sim_viewer first runs a mosaic_domains=100 simulation, then a mosaic_domains=10 simulation.  It should immediately switch to 10.
