### ISSUE TITLE
Use canonical paradigm for the orientation matrix 

### ISSUE THREAD

**Issue by nksauter** [dermen/sim_erice#45]
Let's make sure we are calculating our orientation according to the accepted practice, see David Waterman's 2016 paper at https://doi.org/10.1107/S2059798316002187, equations 12-13:

![Screen Shot 2023-05-23 at 12 09 50 PM](https://github.com/dermen/sim_erice/assets/14790230/52a13ad9-809a-4388-8d63-80b22d3cf491)

Here, the B matrix is an expression of the unit cell parameters in a standard orientation.  U is the rotation matrix returned by the "Randomize Orientation" button.  RxRyRz are small rotations around lab axes entered into the Rotation x,y,z spinner controls. The resulting matrix is "A" which is further modified by R-phi which is the rotation about the goniometer spindle.  

If there is goniometer rotation in the sim_viewer we should indicate which axis is the spindle.

**Comment by nksauter** [comment]
As discussed in today's meeting, this paradigm requires the rotational operations to be applied in a specific order (grouping matrix multiplications from right to left as is conventional in math).  There should actually be a line of code that links all the rotations together:
<strong>A = R<sub>$\phi$</sub>*R<sub>x</sub>*R<sub>y</sub>*R<sub>z</sub>*U<sub>0</sub>*B</strong>
where 
<strong>R<sub>$\phi$</sub></strong> is the goniometer rotation around the laboratory-y spindle, incremented by the Image-no spinner control,
<strong>R<sub>x</sub></strong> is a rotation around laboratory-x given by the rotation-x spinner control,
<strong>R<sub>y</sub></strong> is a rotation around laboratory-y given by the rotation-y spinner control,
<strong>R<sub>z</sub></strong> is a rotation around laboratory-z given by the rotation-z spinner control, and
<strong>U<sub>0</sub></strong> is a pure rotation matrix produced by the Randomize Orientation button that is set to the identity matrix by the Reset-All button.

**Comment by irisdyoung** [comment]
I believe this is correct now. Rot x, y and z are correctly applied according to lines 142-145 of on_the_fly_simdata.py, and U0 is handled separately now.

**Comment by dermen** [comment]
Ill just add (in case we need to change anything) that there's a method called diffBragg::diffBragg_rot_mats() that does:

```
    db_cryst.RXYZ = db_cryst.RotMats[0]*db_cryst.RotMats[1]*db_cryst.RotMats[2];

    /*  update Umats to be U*RXYZ   */
    for(mos_tic=0;mos_tic<mosaic_domains;++mos_tic){
        db_cryst.UMATS_RXYZ[mos_tic] = db_cryst.UMATS[mos_tic] * db_cryst.RXYZ;
```

where RotMats[0] , RotMats[1], RotMats[2] are Rx,Ry,Rz (e.g., when you change the spinner control for Rot_x you are indeed changing RotMats[0]).. This then gets left-multiplied with the A-matrix during modeling: UMATZ_RXYZ * A
