### ISSUE TITLE
Domain size issue

### ISSUE THREAD

**Issue by mewall** [dermen/sim_erice#49]
I'm seeing an issue where the same domain size setting yields different images for otherwise identical control settings

o Open sim_view and immediately load PDB ID 1cm1 (calmodullin)
o Randomize orientation a few times until an image appears where the spots are very elongated. Remember how this looks.
o Increase the domain size to 2000 and decrease it back down to 1000. The image looks different (and perhaps more reasonable)

**Comment by irisdyoung** [comment]
I believe this issue arose with commit 06b1b82158aa6b5ba63fcc95f03135dc6006aa9f and was fixed again by commit f660f7ba1f4a1726c992ce4435f2b1bc666660ec
