### ISSUE TITLE
Implement a detector distance phil parameter

### ISSUE THREAD

**Issue by nksauter** [dermen/sim_erice#52]
Per request from the reviewer let's have a distance phil parameter to set the detector distance, at expert_level=1.  Possibly the pixel size should be a phil parameter too.

**Comment by irisdyoung** [comment]
If we want pixel size (and/or panel dimensions, beam center, etc.) we can instantiate whole_det differently, just overriding some of the dictionary items in its definition in tst_nanoBragg_multipanel.py -- actually fairly simple.
