### ISSUE TITLE
Too much screen output from add_diffBragg_spots()

### ISSUE THREAD

**Issue by nksauter** [dermen/sim_erice#61]
This one is for @dermen .  We agreed that the diffBragg logger output would be printed on screen by the sim_viewer, but it is excessive!  One thing that stands out is that for 100 sources (as for the XFEL case), it prints the direction, weight, and wavelength in meters for each one of them.  This is too much output for a teaching tool.  Please propose an alternative, preferably in a pull request where we can just try it out and merge it.  I expect the code changes might be in cctbx_project.

**Comment by dermen** [comment]
sounds good, ill have a look

**Comment by dermen** [comment]
Was this fixed ? Im seeing a reasonable amount of output on my end:

**Comment by dermen** [comment]
Fixed with https://github.com/dermen/sim_erice/pull/63
