### ISSUE TITLE
Add diffBragg kokkos support

### ISSUE THREAD

**Issue by mewall** [dermen/sim_erice#8]
Need to add the following at the top of sim_view.py when diffBragg is built using kokkos

from simtbx.kokkos import gpu_instance
kokkos_run = gpu_instance(deviceId=0)

**Comment by Trzs** [comment]
Fixed with [39b6835](https://github.com/dermen/sim_erice/commit/39b68355e51a4c70fe80440ff2f895023262f7a7)
